### PR TITLE
fix: google (android)

### PR DESCRIPTION
**Pull request by WcaleNieWolny**
Requires the following change in the `MainActivity.java`

```java
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N && requestCode >= GoogleProvider.REQUEST_AUTHORIZE_GOOGLE_MIN && requestCode < GoogleProvider.REQUEST_AUTHORIZE_GOOGLE_MAX) {
            PluginHandle pluginHandle = getBridge().getPlugin("SocialLogin");
            if (pluginHandle == null) {
                Log.i("Google Activity Result", "SocialLogin login handle is null");
                return;
            }
            Plugin plugin = pluginHandle.getInstance();
            if (!(plugin instanceof SocialLoginPlugin)) {
                Log.i("Google Activity Result", "SocialLogin plugin instance is not SocialLoginPlugin");
                return;
            }
            ((SocialLoginPlugin) plugin).handleGoogleLoginIntent(requestCode, data);
        }
    }
 ```
 
 TODO:
  - [x] Document Google changes on Android

### CODE REVIEW

**Comment by Saqib92** [comment]
Waiting for this update.

**Comment by Saqib92** [comment]
any ETA for this to be merged? November is here and 12th is the deadline..

**Comment by Saqib92** [comment]
I am talking about Apple Privacy Manifest deadline. When i am migrating to this plugin it is throwing some error related to Web other issues. i am assuming this PR this fix them so i can migrate.

**Comment by WcaleNieWolny** [comment]
> We need to support same min version as capacitor

Fixed in https://github.com/Cap-go/capacitor-social-login/pull/37/commits/cffde90bca3ba708fccc56c285733f64b22e4732 and https://github.com/Cap-go/capacitor-social-login/pull/37/commits/4e89adaaf4cdd2e1442412001a23da04e5b9c1ed

**Comment by WcaleNieWolny** [comment]
@Saqib92 I just pushed the changes to replace `CompletableFuture` with `ListenableFuture`. This way this plugin works on all versions of Capacitor.

**Comment by Saqib92** [comment]
It there a way I can test and confirm this PR works as expected?

**Comment by WcaleNieWolny** [comment]
> It there a way I can test and confirm this PR works as expected?

Sure, if you use bun just checkout this branch and run `bun link`. Then, add a
```json
"@capgo/capacitor-social-login": "link:@capgo/capacitor-social-login",
```
into your `dependencies`.

Run `bun i` and `bunx cap sync`. Personally, that is how I test PRs, but you might not be using bun, in which case I don't know how you can test this PR

**Comment by Saqib92** [comment]
> > It there a way I can test and confirm this PR works as expected?
> 
> Sure, if you use bun just checkout this branch and run `bun link`. Then, add a
> 
> ```json
> "@capgo/capacitor-social-login": "link:@capgo/capacitor-social-login",
> ```
> 
> into your `dependencies`.
> 
> Run `bun i` and `bunx cap sync`. Personally, that is how I test PRs, but you might not be using bun, in which case I don't know how you can test this PR

i tried with npm alternative:
`npm install github:Cap-go/capacitor-social-login#pull/37/head`
it installs the plugin but not generation `dist` folder for type definition, making it not useable. 

I think only solution is to release it.

**Comment by WcaleNieWolny** [comment]
I don't have NPM access

CC @riderx

**Comment by Saqib92** [comment]
any ETA for release date?

**Comment by WcaleNieWolny** [comment]
I wanted to release today, but the CI/CD is running pnpm for whatever reason. I am trying to fix the build issues right now

**Comment by WcaleNieWolny** [comment]
I released 0.0.68-alpha.2 with this PR

**Pull request merged**
